//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activity()
        {
            this.LogReadActivities = new HashSet<LogReadActivity>();
        }
    
        public long ActivityId { get; set; }
        public long ActivityTypeId { get; set; }
        public long AuthorId { get; set; }
        public Nullable<long> ChecklistId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<long> MilestoneId { get; set; }
        public Nullable<long> NoteId { get; set; }
        public Nullable<long> ProjectId { get; set; }
        public Nullable<long> ProjectTemplateId { get; set; }
        public Nullable<long> ProjectTemplateMilestoneId { get; set; }
        public Nullable<long> ProjectTemplateTaskId { get; set; }
        public Nullable<long> TaskId { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> WorkstreamId { get; set; }
    
        public virtual ActivityType ActivityType { get; set; }
        public virtual Checklist Checklist { get; set; }
        public virtual Milestone Milestone { get; set; }
        public virtual Note Note { get; set; }
        public virtual Project Project { get; set; }
        public virtual ProjectTemplateMilestone ProjectTemplateMilestone { get; set; }
        public virtual ProjectTemplate ProjectTemplate { get; set; }
        public virtual ProjectTemplateTask ProjectTemplateTask { get; set; }
        public virtual Task Task { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Workstream Workstream { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogReadActivity> LogReadActivities { get; set; }
    }
}
