//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChecklistItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChecklistItem()
        {
            this.ProjectChecklistItemValues = new HashSet<ProjectChecklistItemValue>();
        }
    
        public long ChecklistItemId { get; set; }
        public long ChecklistId { get; set; }
        public string Header { get; set; }
        public bool IsDeleted { get; set; }
        public long ItemIndex { get; set; }
    
        public virtual Checklist Checklist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectChecklistItemValue> ProjectChecklistItemValues { get; set; }
    }
}
