//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImpactedSpec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ImpactedSpec()
        {
            this.ProjectImpactedSpecMonthWiseLogs = new HashSet<ProjectImpactedSpecMonthWiseLog>();
            this.ProjectImpactedSpecs = new HashSet<ProjectImpactedSpec>();
        }
    
        public long ImpactedSpecId { get; set; }
        public Nullable<long> ProjectTypeId { get; set; }
        public string ImpactedSpecName { get; set; }
        public string ImpactedSpecDescription { get; set; }
    
        public virtual ProjectType ProjectType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectImpactedSpecMonthWiseLog> ProjectImpactedSpecMonthWiseLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectImpactedSpec> ProjectImpactedSpecs { get; set; }
    }
}
