//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImpactedSite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ImpactedSite()
        {
            this.PmcSrcmForms = new HashSet<PmcSrcmForm>();
            this.ProjectsImpactedSiteMonthWiseLogs = new HashSet<ProjectsImpactedSiteMonthWiseLog>();
            this.ProjectsImpactedSites = new HashSet<ProjectsImpactedSite>();
            this.ProjectsPMCSRCMMonthwiseLogs = new HashSet<ProjectsPMCSRCMMonthwiseLog>();
            this.ProjectsRMCSRCMMonthwiseLogs = new HashSet<ProjectsRMCSRCMMonthwiseLog>();
            this.RmcSrcmForms = new HashSet<RmcSrcmForm>();
        }
    
        public long ImpactedSiteId { get; set; }
        public string ImpactedSiteName { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PmcSrcmForm> PmcSrcmForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectsImpactedSiteMonthWiseLog> ProjectsImpactedSiteMonthWiseLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectsImpactedSite> ProjectsImpactedSites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectsPMCSRCMMonthwiseLog> ProjectsPMCSRCMMonthwiseLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectsRMCSRCMMonthwiseLog> ProjectsRMCSRCMMonthwiseLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RmcSrcmForm> RmcSrcmForms { get; set; }
    }
}
