//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrackerONEDbEntities : DbContext
    {
        public TrackerONEDbEntities()
            : base("name=TrackerONEDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<ActivityType> ActivityTypes { get; set; }
        public virtual DbSet<Attachment> Attachments { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<ChecklistItem> ChecklistItems { get; set; }
        public virtual DbSet<Checklist> Checklists { get; set; }
        public virtual DbSet<Designation> Designations { get; set; }
        public virtual DbSet<ImpactedSite> ImpactedSites { get; set; }
        public virtual DbSet<ImpactedSpec> ImpactedSpecs { get; set; }
        public virtual DbSet<LogReadActivity> LogReadActivities { get; set; }
        public virtual DbSet<LogReadAlert> LogReadAlerts { get; set; }
        public virtual DbSet<ManagerComment> ManagerComments { get; set; }
        public virtual DbSet<MaterialFollowupItem> MaterialFollowupItems { get; set; }
        public virtual DbSet<Milestone> Milestones { get; set; }
        public virtual DbSet<MiscellaneousForm> MiscellaneousForms { get; set; }
        public virtual DbSet<Note> Notes { get; set; }
        public virtual DbSet<PMCGovernanceForm> PMCGovernanceForms { get; set; }
        public virtual DbSet<PmcSrcmForm> PmcSrcmForms { get; set; }
        public virtual DbSet<ProjectAlert> ProjectAlerts { get; set; }
        public virtual DbSet<ProjectBrandMonthWiseLog> ProjectBrandMonthWiseLogs { get; set; }
        public virtual DbSet<ProjectBrand> ProjectBrands { get; set; }
        public virtual DbSet<ProjectChecklistItemValue> ProjectChecklistItemValues { get; set; }
        public virtual DbSet<ProjectHeaderChangeTypeMonthWiseLog> ProjectHeaderChangeTypeMonthWiseLogs { get; set; }
        public virtual DbSet<ProjectHeaderChangeType> ProjectHeaderChangeTypes { get; set; }
        public virtual DbSet<ProjectImpactedSpecMonthWiseLog> ProjectImpactedSpecMonthWiseLogs { get; set; }
        public virtual DbSet<ProjectImpactedSpec> ProjectImpactedSpecs { get; set; }
        public virtual DbSet<ProjectOperationStatu> ProjectOperationStatus { get; set; }
        public virtual DbSet<ProjectPriority> ProjectPriorities { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<ProjectsImpactedSiteMonthWiseLog> ProjectsImpactedSiteMonthWiseLogs { get; set; }
        public virtual DbSet<ProjectsImpactedSite> ProjectsImpactedSites { get; set; }
        public virtual DbSet<ProjectsMonthwiseLog> ProjectsMonthwiseLogs { get; set; }
        public virtual DbSet<ProjectsPMCSRCMMonthwiseLog> ProjectsPMCSRCMMonthwiseLogs { get; set; }
        public virtual DbSet<ProjectsRMCSRCMMonthwiseLog> ProjectsRMCSRCMMonthwiseLogs { get; set; }
        public virtual DbSet<ProjectStatu> ProjectStatus { get; set; }
        public virtual DbSet<ProjectSupplierMonthWiseLog> ProjectSupplierMonthWiseLogs { get; set; }
        public virtual DbSet<ProjectSupplier> ProjectSuppliers { get; set; }
        public virtual DbSet<ProjectTemplateForm> ProjectTemplateForms { get; set; }
        public virtual DbSet<ProjectTemplateMilestone> ProjectTemplateMilestones { get; set; }
        public virtual DbSet<ProjectTemplate> ProjectTemplates { get; set; }
        public virtual DbSet<ProjectTemplateTask> ProjectTemplateTasks { get; set; }
        public virtual DbSet<ProjectType> ProjectTypes { get; set; }
        public virtual DbSet<RecentProjectInfo> RecentProjectInfoes { get; set; }
        public virtual DbSet<RmcGovernanceForm> RmcGovernanceForms { get; set; }
        public virtual DbSet<RmcSrcmForm> RmcSrcmForms { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<TaskStatu> TaskStatus { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserSetting> UserSettings { get; set; }
        public virtual DbSet<Workstream> Workstreams { get; set; }
        public virtual DbSet<SampleView> SampleViews { get; set; }
        public virtual DbSet<ViewProjectDetail> ViewProjectDetails { get; set; }
    }
}
