//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectData
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogReadAlert
    {
        public long LogReadAlertId { get; set; }
        public long ProjectAlertId { get; set; }
        public long UserId { get; set; }
        public System.DateTime ReadOn { get; set; }
    
        public virtual ProjectAlert ProjectAlert { get; set; }
        public virtual User User { get; set; }
    }
}
