//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialFollowupItem
    {
        public long MaterialFollowupItemId { get; set; }
        public string Name { get; set; }
        public Nullable<long> PMCGovernanceFormId { get; set; }
        public Nullable<long> RmcGovernanceFormId { get; set; }
    
        public virtual PMCGovernanceForm PMCGovernanceForm { get; set; }
        public virtual RmcGovernanceForm RmcGovernanceForm { get; set; }
    }
}
