//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MiscellaneousForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MiscellaneousForm()
        {
            this.ProjectBrands = new HashSet<ProjectBrand>();
            this.ProjectHeaderChangeTypes = new HashSet<ProjectHeaderChangeType>();
            this.ProjectImpactedSpecs = new HashSet<ProjectImpactedSpec>();
            this.ProjectsImpactedSites = new HashSet<ProjectsImpactedSite>();
            this.ProjectSuppliers = new HashSet<ProjectSupplier>();
        }
    
        public long MiscellaneousFormId { get; set; }
        public Nullable<System.DateTime> ActualCompletionDate { get; set; }
        public Nullable<System.DateTime> DateOfTransfer { get; set; }
        public Nullable<long> ImportedTypeId { get; set; }
        public string InventoryCustom1 { get; set; }
        public string InventoryCustom2 { get; set; }
        public string InventoryCustom3 { get; set; }
        public string InventoryCustom4 { get; set; }
        public string InventoryCustom5 { get; set; }
        public Nullable<System.DateTime> InventoryDepletionDate { get; set; }
        public string InventoryDepletionDateComment { get; set; }
        public string InventorySecuredComment { get; set; }
        public Nullable<bool> IsInventorySecured { get; set; }
        public Nullable<int> IsQAAssigned { get; set; }
        public Nullable<int> IsRRTAssigned { get; set; }
        public Nullable<int> IsSOARAssigned { get; set; }
        public Nullable<int> IsTAAssigned { get; set; }
        public Nullable<System.DateTime> OriginalNotice { get; set; }
        public string OtherChangeTypeComment { get; set; }
        public Nullable<System.DateTime> PlannedCompletionDate { get; set; }
        public Nullable<System.DateTime> ProjectCustomDate1 { get; set; }
        public Nullable<System.DateTime> ProjectCustomDate2 { get; set; }
        public Nullable<System.DateTime> ProjectCustomDate3 { get; set; }
        public string ProjectHeaderCustom1 { get; set; }
        public string ProjectHeaderCustom10 { get; set; }
        public string ProjectHeaderCustom2 { get; set; }
        public string ProjectHeaderCustom3 { get; set; }
        public string ProjectHeaderCustom4 { get; set; }
        public string ProjectHeaderCustom5 { get; set; }
        public string ProjectHeaderCustom6 { get; set; }
        public string ProjectHeaderCustom7 { get; set; }
        public string ProjectHeaderCustom8 { get; set; }
        public string ProjectHeaderCustom9 { get; set; }
        public long ProjectId { get; set; }
        public string ProjectImpactCustom1 { get; set; }
        public string ProjectImpactCustom2 { get; set; }
        public string ProjectImpactCustom3 { get; set; }
        public Nullable<long> ProjectResourceCustomId1 { get; set; }
        public Nullable<long> ProjectResourceCustomId2 { get; set; }
        public Nullable<long> ProjectResourceCustomId3 { get; set; }
        public Nullable<long> QAId { get; set; }
        public Nullable<long> RRTEscalatedUserId { get; set; }
        public Nullable<long> RRTId { get; set; }
        public Nullable<System.DateTime> RRTUserDate { get; set; }
        public Nullable<long> SOARId { get; set; }
        public Nullable<long> TAId { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ProjectType ProjectType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual User User3 { get; set; }
        public virtual User User4 { get; set; }
        public virtual User User5 { get; set; }
        public virtual User User6 { get; set; }
        public virtual User User7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectBrand> ProjectBrands { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectHeaderChangeType> ProjectHeaderChangeTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectImpactedSpec> ProjectImpactedSpecs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectsImpactedSite> ProjectsImpactedSites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectSupplier> ProjectSuppliers { get; set; }
    }
}
