//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMCGovernanceForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PMCGovernanceForm()
        {
            this.MaterialFollowupItems = new HashSet<MaterialFollowupItem>();
            this.ProjectBrands = new HashSet<ProjectBrand>();
            this.ProjectSuppliers = new HashSet<ProjectSupplier>();
        }
    
        public long PMCGovernanceFormId { get; set; }
        public string ApprovedSupplierMfgLocation { get; set; }
        public string AuditRating { get; set; }
        public string Benchmark { get; set; }
        public string ColorCount { get; set; }
        public string CommercializationManager { get; set; }
        public string CommodityCategoryAccuracy { get; set; }
        public Nullable<long> CommodityCategoryId { get; set; }
        public string CommodityManagerComments { get; set; }
        public string Costing { get; set; }
        public string Deco { get; set; }
        public Nullable<long> DualSourceBCP { get; set; }
        public string FillSite { get; set; }
        public string FinalAnnualQuantities { get; set; }
        public string FinalLaunchQuantities { get; set; }
        public string FinancialRiskRating { get; set; }
        public Nullable<long> FranchiseId { get; set; }
        public string GensightNumber { get; set; }
        public Nullable<System.DateTime> GovMeetingDate { get; set; }
        public string InitialAnnualForecast { get; set; }
        public string InitialLaunchForecast { get; set; }
        public Nullable<bool> IsApprovedByGovernanceBoard { get; set; }
        public Nullable<bool> IsApprovedBySteeringCommittee { get; set; }
        public string IsMitigationPlanNeeded { get; set; }
        public Nullable<bool> IsNewPCAccepted { get; set; }
        public Nullable<bool> IsNotificationRequired { get; set; }
        public string IsProprietary { get; set; }
        public Nullable<bool> IsReviewedByGovernanceBoard { get; set; }
        public Nullable<bool> IsReviewedBySteeringCommittee { get; set; }
        public Nullable<long> ManagerCommentId { get; set; }
        public Nullable<long> MaterialTypeId { get; set; }
        public string MinimumOrderQuantity { get; set; }
        public string NewSupplierLocation { get; set; }
        public string PackagingEngineer { get; set; }
        public string PCSpecReference { get; set; }
        public string PkgEngComments { get; set; }
        public string ProcurementComments { get; set; }
        public long ProjectId { get; set; }
        public string ProjectReason { get; set; }
        public Nullable<long> ProjectTypeId { get; set; }
        public Nullable<long> QQRequestTypeId { get; set; }
        public string QRAStatus { get; set; }
        public string QualityComments { get; set; }
        public string QualitySupplierSegment { get; set; }
        public string RequestedSupplier { get; set; }
        public string Requestor { get; set; }
        public Nullable<System.DateTime> ShipToTradeDate { get; set; }
        public Nullable<long> SizeCode { get; set; }
        public string SKUDescription { get; set; }
        public string SourceApprovedSupplier { get; set; }
        public Nullable<long> StandardizationTypeId { get; set; }
        public string StandardLeadTime { get; set; }
        public string SuggestedMinimumOrderQuantity { get; set; }
        public string SupplierLocationStatus { get; set; }
        public string SupplierName { get; set; }
        public string SupplierRiskRating { get; set; }
        public string SupplierSegment { get; set; }
        public string VarnishType { get; set; }
    
        public virtual ManagerComment ManagerComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialFollowupItem> MaterialFollowupItems { get; set; }
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectBrand> ProjectBrands { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectSupplier> ProjectSuppliers { get; set; }
    }
}
