//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectsRMCSRCMMonthwiseLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectsRMCSRCMMonthwiseLog()
        {
            this.ProjectBrandMonthWiseLogs = new HashSet<ProjectBrandMonthWiseLog>();
            this.ProjectHeaderChangeTypeMonthWiseLogs = new HashSet<ProjectHeaderChangeTypeMonthWiseLog>();
            this.ProjectImpactedSpecMonthWiseLogs = new HashSet<ProjectImpactedSpecMonthWiseLog>();
            this.ProjectsImpactedSiteMonthWiseLogs = new HashSet<ProjectsImpactedSiteMonthWiseLog>();
            this.ProjectSupplierMonthWiseLogs = new HashSet<ProjectSupplierMonthWiseLog>();
        }
    
        public long ProjectsRMCSRCMMonthwiseLogId { get; set; }
        public Nullable<System.DateTime> ActualCompletionDate { get; set; }
        public Nullable<long> AlternateSpecs { get; set; }
        public string AlternateSupplier { get; set; }
        public string AnalysisCertificate { get; set; }
        public string AnalyticalOrStability { get; set; }
        public Nullable<long> AuditStatusId { get; set; }
        public string CCNumber { get; set; }
        public string ChangeRequestFormRequired { get; set; }
        public string ClaimSupport { get; set; }
        public string ClinicalClearance { get; set; }
        public string CriticalPath { get; set; }
        public string CriticalPathOwners { get; set; }
        public string CurrentSupplier { get; set; }
        public Nullable<long> CycleTime { get; set; }
        public Nullable<System.DateTime> DateOfTransfer { get; set; }
        public string DaysMemoRequest { get; set; }
        public string DesignControlApproval { get; set; }
        public string DocumentUpdate { get; set; }
        public Nullable<System.DateTime> EffectiveDateChange { get; set; }
        public string EnvironmentalEvaluation { get; set; }
        public string EquivalencyStatement { get; set; }
        public string GCCNumber { get; set; }
        public Nullable<long> ImpactedBrandId { get; set; }
        public Nullable<System.DateTime> InitialCompletionDate { get; set; }
        public Nullable<long> InventoryDateDepletion { get; set; }
        public Nullable<System.DateTime> InventoryDepletionDate { get; set; }
        public string InventoryDepletionDateComment { get; set; }
        public string InventorySecuredComment { get; set; }
        public Nullable<long> InventorySecuredVolume { get; set; }
        public Nullable<bool> IsInventoryProject { get; set; }
        public Nullable<bool> IsOnSiteAuditRequired { get; set; }
        public Nullable<bool> IsOptivaWorkflowInitiated { get; set; }
        public Nullable<int> IsQAAssigned { get; set; }
        public Nullable<bool> IsQQRequestRequired { get; set; }
        public Nullable<bool> IsRMQRequested { get; set; }
        public Nullable<int> IsRRTAssigned { get; set; }
        public Nullable<bool> IsSecureInventory { get; set; }
        public Nullable<int> IsSOARAssigned { get; set; }
        public Nullable<int> IsTAAssigned { get; set; }
        public Nullable<bool> IsWatchListItem { get; set; }
        public Nullable<System.DateTime> LatestCompletionDate { get; set; }
        public string LatestUpdate { get; set; }
        public string LegalReview { get; set; }
        public string MalfunctionListsUpdate { get; set; }
        public string MicroClearance { get; set; }
        public string MicroEvaluation { get; set; }
        public Nullable<long> NotificationTypeId { get; set; }
        public string OnSiteAdditionalComments { get; set; }
        public Nullable<bool> OptivaEntryVendorStatus { get; set; }
        public Nullable<System.DateTime> OriginalNoticeDate { get; set; }
        public string OtherChangeType { get; set; }
        public string PackagingClearance { get; set; }
        public string PilotValidation { get; set; }
        public string PreclinicalClearance { get; set; }
        public string PriorityJustification { get; set; }
        public string ProductAndProcessDevelopment { get; set; }
        public Nullable<long> ProjectHeaderChangeTypeId { get; set; }
        public long ProjectId { get; set; }
        public Nullable<long> ProjectResourceCustomUserId1 { get; set; }
        public Nullable<long> ProjectResourceCustomUserId2 { get; set; }
        public Nullable<long> ProjectResourceCustomUserId3 { get; set; }
        public long ProjectsMonthwiseLogId { get; set; }
        public string ProjectType { get; set; }
        public string QALead { get; set; }
        public Nullable<long> QALeadId { get; set; }
        public Nullable<System.DateTime> QualificationStartedDate { get; set; }
        public string QualityAssuranceClearance { get; set; }
        public string ReviewofSupplierRiskRating { get; set; }
        public string RightToMarket { get; set; }
        public string RiskAnalysisOrAssessment { get; set; }
        public long RmcSrcmFormId { get; set; }
        public Nullable<long> RRTLeadId { get; set; }
        public Nullable<long> RRTLogEscalatedUserId { get; set; }
        public Nullable<System.DateTime> RRTUserDate { get; set; }
        public string SAPMasterData { get; set; }
        public Nullable<long> SitesImpactedId { get; set; }
        public string SOaRLead { get; set; }
        public Nullable<long> SOaRLeadId { get; set; }
        public string SpecificationChange { get; set; }
        public string SpecificationUpdates { get; set; }
        public string SpecsImpacted { get; set; }
        public string StabilityTestingDevelopmental { get; set; }
        public string StabilityTestingMarketed { get; set; }
        public string SterileProductSelection { get; set; }
        public Nullable<System.DateTime> SupplierImplementationDate { get; set; }
        public string SupplierMemo { get; set; }
        public string SVPMemoRequest { get; set; }
        public Nullable<long> TALeadId { get; set; }
        public string TechnicalAssessment { get; set; }
        public string TechnicalDossierUpdate { get; set; }
        public string TechnicalJustification { get; set; }
        public string TechSummary { get; set; }
        public string TestMethodTransferValidation { get; set; }
        public string ToxicologyOrSafetyAssesment { get; set; }
        public string UpdateToApprovedSupplierList { get; set; }
        public Nullable<long> WatchListType { get; set; }
    
        public virtual ImpactedSite ImpactedSite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectBrandMonthWiseLog> ProjectBrandMonthWiseLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectHeaderChangeTypeMonthWiseLog> ProjectHeaderChangeTypeMonthWiseLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectImpactedSpecMonthWiseLog> ProjectImpactedSpecMonthWiseLogs { get; set; }
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectsImpactedSiteMonthWiseLog> ProjectsImpactedSiteMonthWiseLogs { get; set; }
        public virtual ProjectsMonthwiseLog ProjectsMonthwiseLog { get; set; }
        public virtual RmcSrcmForm RmcSrcmForm { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual User User3 { get; set; }
        public virtual User User4 { get; set; }
        public virtual User User5 { get; set; }
        public virtual User User6 { get; set; }
        public virtual User User7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectSupplierMonthWiseLog> ProjectSupplierMonthWiseLogs { get; set; }
    }
}
