//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectImpactedSpec
    {
        public long ProjectImpactedSpecId { get; set; }
        public Nullable<long> RmcSrcmFormId { get; set; }
        public Nullable<long> PmcSrcmFormId { get; set; }
        public long ImpactedSpecId { get; set; }
        public Nullable<long> MiscellaneousFormId { get; set; }
    
        public virtual ImpactedSpec ImpactedSpec { get; set; }
        public virtual MiscellaneousForm MiscellaneousForm { get; set; }
        public virtual PmcSrcmForm PmcSrcmForm { get; set; }
        public virtual RmcSrcmForm RmcSrcmForm { get; set; }
    }
}
