//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectSupplier
    {
        public long ProjectSupplierId { get; set; }
        public Nullable<long> RmcSrcmFormId { get; set; }
        public Nullable<long> PmcSrcmFormId { get; set; }
        public Nullable<long> RmcGovernanceFormId { get; set; }
        public Nullable<long> PMCGovernanceFormId { get; set; }
        public Nullable<long> MiscellaneousFormId { get; set; }
        public long SupplierId { get; set; }
    
        public virtual MiscellaneousForm MiscellaneousForm { get; set; }
        public virtual PMCGovernanceForm PMCGovernanceForm { get; set; }
        public virtual PmcSrcmForm PmcSrcmForm { get; set; }
        public virtual RmcGovernanceForm RmcGovernanceForm { get; set; }
        public virtual RmcSrcmForm RmcSrcmForm { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
