//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectsPMCSRCMMonthwiseLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectsPMCSRCMMonthwiseLog()
        {
            this.ProjectBrandMonthWiseLogs = new HashSet<ProjectBrandMonthWiseLog>();
            this.ProjectHeaderChangeTypeMonthWiseLogs = new HashSet<ProjectHeaderChangeTypeMonthWiseLog>();
            this.ProjectImpactedSpecMonthWiseLogs = new HashSet<ProjectImpactedSpecMonthWiseLog>();
            this.ProjectsImpactedSiteMonthWiseLogs = new HashSet<ProjectsImpactedSiteMonthWiseLog>();
            this.ProjectSupplierMonthWiseLogs = new HashSet<ProjectSupplierMonthWiseLog>();
        }
    
        public long ProjectsPMCSRCMMonthwiseLogId { get; set; }
        public Nullable<long> RRTEscalatedUserId { get; set; }
        public Nullable<System.DateTime> ActualCompletionDate { get; set; }
        public string AlternateSpec { get; set; }
        public string AlternateSupplier { get; set; }
        public Nullable<bool> AreSamplesTested { get; set; }
        public Nullable<long> AuditStatusId { get; set; }
        public string BatchReception { get; set; }
        public string BatchRequest { get; set; }
        public Nullable<long> BrandsTypeId { get; set; }
        public string CCCForm { get; set; }
        public Nullable<long> CommodityCategoryId { get; set; }
        public Nullable<long> CommodityManagerId { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public string CurrentSupplier { get; set; }
        public Nullable<long> CycleTime { get; set; }
        public Nullable<System.DateTime> DateOfTransfer { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<long> GCCNumber { get; set; }
        public Nullable<System.DateTime> InventoryDepletionDate { get; set; }
        public string InventoryDepletionDateComment { get; set; }
        public string InventoryNeededComments { get; set; }
        public string InventorySecuredComment { get; set; }
        public Nullable<bool> Is65DaysSVPMemoRequested { get; set; }
        public Nullable<bool> IsAlternativePackageNeeded { get; set; }
        public Nullable<bool> IsCOAorCFCRequested { get; set; }
        public Nullable<int> IsCommodityManagerAssigned { get; set; }
        public Nullable<bool> IsDevelopmentalStabilityConducted { get; set; }
        public Nullable<bool> IsEquivalencyMemoNeeded { get; set; }
        public Nullable<bool> IsInventoryProject { get; set; }
        public Nullable<bool> IsLineTrialConducted { get; set; }
        public Nullable<bool> IsMarketedProductStabilityConducted { get; set; }
        public Nullable<bool> IsOnSiteAuditeRequired { get; set; }
        public Nullable<bool> IsPackageAcceptable { get; set; }
        public Nullable<int> IsPEAssigned { get; set; }
        public Nullable<bool> IsPEGCCApproved { get; set; }
        public Nullable<bool> IsPEGCCExecuted { get; set; }
        public Nullable<bool> IsPEGCCPlanCreated { get; set; }
        public Nullable<bool> IsPilotBatchingConducted { get; set; }
        public Nullable<int> IsPMOAssigned { get; set; }
        public Nullable<bool> IsQQRequestRequired { get; set; }
        public Nullable<int> IsRRTAssigned { get; set; }
        public Nullable<bool> IsSAPMasterDataUpdated { get; set; }
        public Nullable<bool> IsSecureInventory { get; set; }
        public Nullable<int> IsSOARAssigned { get; set; }
        public Nullable<bool> IsSOaRGCCApproved { get; set; }
        public Nullable<bool> IsSOaRGCCExecuted { get; set; }
        public Nullable<bool> IsSOaRGCCInitiated { get; set; }
        public Nullable<bool> IsSpecificationUpdated { get; set; }
        public Nullable<int> IsSQAAssigned { get; set; }
        public Nullable<bool> IsSupplierMemoRequested { get; set; }
        public Nullable<bool> IsSVPMemoRequested { get; set; }
        public Nullable<bool> IsTechnicalJustificationCreated { get; set; }
        public Nullable<bool> IsToxicologyMemoAssessed { get; set; }
        public Nullable<bool> IsWatchListProject { get; set; }
        public Nullable<System.DateTime> NotificationDate { get; set; }
        public Nullable<long> NotificationTypeId { get; set; }
        public string OtherChangeType { get; set; }
        public Nullable<long> PCCNumber { get; set; }
        public string PCsImpacted { get; set; }
        public Nullable<long> PELeadId { get; set; }
        public Nullable<System.DateTime> PlannedCompletionDate { get; set; }
        public long PmcSrcmFormId { get; set; }
        public string PMO { get; set; }
        public Nullable<long> PMOLeadId { get; set; }
        public string PriorityJustification { get; set; }
        public Nullable<System.DateTime> ProjectCustomDate1 { get; set; }
        public Nullable<System.DateTime> ProjectCustomDate2 { get; set; }
        public Nullable<System.DateTime> ProjectCustomDate3 { get; set; }
        public string ProjectCustomInventory1 { get; set; }
        public string ProjectCustomInventory2 { get; set; }
        public string ProjectCustomInventory3 { get; set; }
        public string ProjectCustomInventory4 { get; set; }
        public string ProjectCustomInventory5 { get; set; }
        public Nullable<long> ProjectHeaderChangeTypeId { get; set; }
        public string ProjectHeaderCustom1 { get; set; }
        public string ProjectHeaderCustom10 { get; set; }
        public string ProjectHeaderCustom2 { get; set; }
        public string ProjectHeaderCustom3 { get; set; }
        public string ProjectHeaderCustom4 { get; set; }
        public string ProjectHeaderCustom5 { get; set; }
        public string ProjectHeaderCustom6 { get; set; }
        public string ProjectHeaderCustom7 { get; set; }
        public string ProjectHeaderCustom8 { get; set; }
        public string ProjectHeaderCustom9 { get; set; }
        public long ProjectId { get; set; }
        public string ProjectImpactCustom1 { get; set; }
        public string ProjectImpactCustom2 { get; set; }
        public string ProjectImpactCustom3 { get; set; }
        public Nullable<long> ProjectResourceCustomUserId1 { get; set; }
        public Nullable<long> ProjectResourceCustomUserId2 { get; set; }
        public Nullable<long> ProjectResourceCustomUserId3 { get; set; }
        public long ProjectsMonthwiseLogId { get; set; }
        public string ProjectType { get; set; }
        public string RRT { get; set; }
        public Nullable<long> RRTLeadId { get; set; }
        public Nullable<System.DateTime> RRTUserDate { get; set; }
        public string SecureInventoryVolume { get; set; }
        public Nullable<long> SitesImpactedId { get; set; }
        public string SOaRLead { get; set; }
        public Nullable<long> SOaRLeadId { get; set; }
        public Nullable<long> SQALeadId { get; set; }
        public string SupplierQualitySiteAssessment { get; set; }
        public Nullable<long> WatchListType { get; set; }
    
        public virtual ImpactedSite ImpactedSite { get; set; }
        public virtual PmcSrcmForm PmcSrcmForm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectBrandMonthWiseLog> ProjectBrandMonthWiseLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectHeaderChangeTypeMonthWiseLog> ProjectHeaderChangeTypeMonthWiseLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectImpactedSpecMonthWiseLog> ProjectImpactedSpecMonthWiseLogs { get; set; }
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectsImpactedSiteMonthWiseLog> ProjectsImpactedSiteMonthWiseLogs { get; set; }
        public virtual ProjectsMonthwiseLog ProjectsMonthwiseLog { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual User User3 { get; set; }
        public virtual User User4 { get; set; }
        public virtual User User5 { get; set; }
        public virtual User User6 { get; set; }
        public virtual User User7 { get; set; }
        public virtual User User8 { get; set; }
        public virtual User User9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectSupplierMonthWiseLog> ProjectSupplierMonthWiseLogs { get; set; }
    }
}
