//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectChecklistItemValue
    {
        public long ProjectChecklistItemValueId { get; set; }
        public long ChecklistItemId { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> IsYes { get; set; }
        public Nullable<bool> IsNotApplicable { get; set; }
        public long ProjectId { get; set; }
        public Nullable<System.DateTime> ItemDate { get; set; }
        public long DisplayOrder { get; set; }
    
        public virtual ChecklistItem ChecklistItem { get; set; }
        public virtual Project Project { get; set; }
    }
}
