//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectsMonthwiseLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectsMonthwiseLog()
        {
            this.ProjectsPMCSRCMMonthwiseLogs = new HashSet<ProjectsPMCSRCMMonthwiseLog>();
            this.ProjectsRMCSRCMMonthwiseLogs = new HashSet<ProjectsRMCSRCMMonthwiseLog>();
        }
    
        public long ProjectsMonthwiseLogId { get; set; }
        public Nullable<System.DateTime> ActualEndDate { get; set; }
        public Nullable<System.DateTime> ActualStartDate { get; set; }
        public long CompletedTasksCount { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsDateChangeBlocked { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<long> LogDateMonth { get; set; }
        public Nullable<long> LogDateYear { get; set; }
        public double PercentComplete { get; set; }
        public Nullable<long> ProjectCoordinatorId { get; set; }
        public string ProjectDisplayId { get; set; }
        public long ProjectId { get; set; }
        public Nullable<long> ProjectManagerId { get; set; }
        public string ProjectName { get; set; }
        public long ProjectOperationStatusId { get; set; }
        public long ProjectPriorityId { get; set; }
        public long ProjectStatusId { get; set; }
        public string ProjectSummary { get; set; }
        public Nullable<long> ProjectTypeId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<long> SupplierId { get; set; }
    
        public virtual ProjectOperationStatu ProjectOperationStatu { get; set; }
        public virtual ProjectPriority ProjectPriority { get; set; }
        public virtual Project Project { get; set; }
        public virtual ProjectStatu ProjectStatu { get; set; }
        public virtual ProjectType ProjectType { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectsPMCSRCMMonthwiseLog> ProjectsPMCSRCMMonthwiseLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectsRMCSRCMMonthwiseLog> ProjectsRMCSRCMMonthwiseLogs { get; set; }
    }
}
