//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectTemplateTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectTemplateTask()
        {
            this.Activities = new HashSet<Activity>();
            this.ProjectTemplateTasks1 = new HashSet<ProjectTemplateTask>();
            this.ProjectTemplateTasks = new HashSet<ProjectTemplateTask>();
        }
    
        public long ProjectTemplateTaskId { get; set; }
        public Nullable<System.DateTime> ActualEndDate { get; set; }
        public Nullable<System.DateTime> ActualStartDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> FixedCost { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public long MilestoneId { get; set; }
        public double PercentComplete { get; set; }
        public long ProjectTemplateId { get; set; }
        public long ProjectTemplateMilestoneId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string TaskDescription { get; set; }
        public string TaskDisplayId { get; set; }
        public string TaskName { get; set; }
        public long TaskNumber { get; set; }
        public Nullable<long> TaskStatusId { get; set; }
        public Nullable<decimal> VariableCost { get; set; }
        public Nullable<long> WorkstreamId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual ProjectTemplateMilestone ProjectTemplateMilestone { get; set; }
        public virtual ProjectTemplate ProjectTemplate { get; set; }
        public virtual Workstream Workstream { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectTemplateTask> ProjectTemplateTasks1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectTemplateTask> ProjectTemplateTasks { get; set; }
    }
}
