//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectTemplate()
        {
            this.Activities = new HashSet<Activity>();
            this.Milestones = new HashSet<Milestone>();
            this.ProjectTemplateForms = new HashSet<ProjectTemplateForm>();
            this.ProjectTemplateMilestones = new HashSet<ProjectTemplateMilestone>();
            this.ProjectTemplateTasks = new HashSet<ProjectTemplateTask>();
        }
    
        public long ProjectTemplateId { get; set; }
        public Nullable<System.DateTime> ActualEndDate { get; set; }
        public Nullable<System.DateTime> ActualStartDate { get; set; }
        public long AuthorId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> IsDateChangeBlocked { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> LastMilestoneSNo { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public double PercentComplete { get; set; }
        public Nullable<long> ProjectCoordinatorId { get; set; }
        public Nullable<long> ProjectManagerId { get; set; }
        public string ProjectName { get; set; }
        public Nullable<long> ProjectOperationStatusId { get; set; }
        public long ProjectPriorityId { get; set; }
        public long ProjectStatusId { get; set; }
        public string ProjectSummary { get; set; }
        public string ProjectTemplateName { get; set; }
        public Nullable<long> ProjectTypeId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<long> SupplierId { get; set; }
        public string TemplateDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Milestone> Milestones { get; set; }
        public virtual ProjectOperationStatu ProjectOperationStatu { get; set; }
        public virtual ProjectPriority ProjectPriority { get; set; }
        public virtual ProjectStatu ProjectStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectTemplateForm> ProjectTemplateForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectTemplateMilestone> ProjectTemplateMilestones { get; set; }
        public virtual ProjectType ProjectType { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectTemplateTask> ProjectTemplateTasks { get; set; }
    }
}
