//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.Activities = new HashSet<Activity>();
            this.Attachments = new HashSet<Attachment>();
            this.Milestones = new HashSet<Milestone>();
            this.MiscellaneousForms = new HashSet<MiscellaneousForm>();
            this.Notes = new HashSet<Note>();
            this.PMCGovernanceForms = new HashSet<PMCGovernanceForm>();
            this.PmcSrcmForms = new HashSet<PmcSrcmForm>();
            this.ProjectAlerts = new HashSet<ProjectAlert>();
            this.ProjectChecklistItemValues = new HashSet<ProjectChecklistItemValue>();
            this.ProjectsMonthwiseLogs = new HashSet<ProjectsMonthwiseLog>();
            this.ProjectsPMCSRCMMonthwiseLogs = new HashSet<ProjectsPMCSRCMMonthwiseLog>();
            this.ProjectsRMCSRCMMonthwiseLogs = new HashSet<ProjectsRMCSRCMMonthwiseLog>();
            this.RmcGovernanceForms = new HashSet<RmcGovernanceForm>();
            this.RmcSrcmForms = new HashSet<RmcSrcmForm>();
            this.Tasks = new HashSet<Task>();
            this.UserSettings = new HashSet<UserSetting>();
        }
    
        public long ProjectId { get; set; }
        public Nullable<System.DateTime> ActualEndDate { get; set; }
        public Nullable<System.DateTime> ActualStartDate { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> InProgressDate { get; set; }
        public bool IsDateChangeBlocked { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsMigrated { get; set; }
        public bool IsMilestoneTemplateSpecified { get; set; }
        public Nullable<long> LastMilestoneSNo { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public double PercentComplete { get; set; }
        public Nullable<long> ProjectCoordinatorId { get; set; }
        public string ProjectDisplayId { get; set; }
        public Nullable<long> ProjectManagerId { get; set; }
        public string ProjectName { get; set; }
        public long ProjectOperationStatusId { get; set; }
        public long ProjectPriorityId { get; set; }
        public long ProjectStatusId { get; set; }
        public string ProjectSummary { get; set; }
        public Nullable<long> ProjectTypeId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<long> SupplierId { get; set; }
        public Nullable<int> TransferStatus { get; set; }
        public string TransferStatusMessage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attachment> Attachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Milestone> Milestones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MiscellaneousForm> MiscellaneousForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Note> Notes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMCGovernanceForm> PMCGovernanceForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PmcSrcmForm> PmcSrcmForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectAlert> ProjectAlerts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectChecklistItemValue> ProjectChecklistItemValues { get; set; }
        public virtual ProjectOperationStatu ProjectOperationStatu { get; set; }
        public virtual ProjectPriority ProjectPriority { get; set; }
        public virtual ProjectStatu ProjectStatu { get; set; }
        public virtual ProjectType ProjectType { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectsMonthwiseLog> ProjectsMonthwiseLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectsPMCSRCMMonthwiseLog> ProjectsPMCSRCMMonthwiseLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectsRMCSRCMMonthwiseLog> ProjectsRMCSRCMMonthwiseLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RmcGovernanceForm> RmcGovernanceForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RmcSrcmForm> RmcSrcmForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSetting> UserSettings { get; set; }
    }
}
