//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RmcGovernanceForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RmcGovernanceForm()
        {
            this.MaterialFollowupItems = new HashSet<MaterialFollowupItem>();
            this.ProjectBrands = new HashSet<ProjectBrand>();
            this.ProjectSuppliers = new HashSet<ProjectSupplier>();
        }
    
        public long RmcGovernanceFormId { get; set; }
        public string AdditionalInfo { get; set; }
        public string AdditionalProjectType { get; set; }
        public Nullable<bool> AlignmentWithQSP { get; set; }
        public Nullable<long> AuditStatus { get; set; }
        public string BrandName { get; set; }
        public Nullable<bool> ConsideredAlternateMaterial { get; set; }
        public Nullable<long> DesignTeamId { get; set; }
        public Nullable<long> DualSourceOrBCP { get; set; }
        public string ExpectedAnnualVolume { get; set; }
        public string FinancialRiskRating { get; set; }
        public Nullable<System.DateTime> GovernaceBoardReviewDate { get; set; }
        public Nullable<System.DateTime> GovernanceBoardApproveDate { get; set; }
        public Nullable<System.DateTime> GovernanceMeetingDate { get; set; }
        public string INCI { get; set; }
        public string INCITechnicalAssessment { get; set; }
        public string InitialRiskRatingProfile { get; set; }
        public Nullable<bool> IsApprovedByGB { get; set; }
        public Nullable<bool> IsApprovedBySC { get; set; }
        public Nullable<bool> IsFormulaCompendial { get; set; }
        public Nullable<bool> IsMonographExists { get; set; }
        public Nullable<bool> IsNewJJSupplier { get; set; }
        public Nullable<bool> IsNewManufacturingSite { get; set; }
        public Nullable<bool> IsNewMaterial { get; set; }
        public Nullable<bool> IsNewNASupplier { get; set; }
        public Nullable<bool> IsNewPCAccepted { get; set; }
        public Nullable<bool> IsNewRMFromExistingSite { get; set; }
        public Nullable<bool> IsOTCProduct { get; set; }
        public Nullable<bool> IsPartOfChassis { get; set; }
        public Nullable<bool> IsProprietary { get; set; }
        public Nullable<bool> IsReviewdBySC { get; set; }
        public Nullable<bool> IsReviewedByGB { get; set; }
        public string JustificationForMaterialUsage { get; set; }
        public string ManufacturingLocation { get; set; }
        public string MaterialGrade { get; set; }
        public string MaterialSubstitution { get; set; }
        public Nullable<long> MicroRiskRating { get; set; }
        public Nullable<bool> NeedRiskMigitationPlan { get; set; }
        public string OnMarketPeriod { get; set; }
        public string OwnerName { get; set; }
        public string PDPartner { get; set; }
        public string ProductRegulatoryClassification { get; set; }
        public string ProjectFormulaStatus { get; set; }
        public long ProjectId { get; set; }
        public string QRAStatus { get; set; }
        public string RaMPSAlignment { get; set; }
        public Nullable<long> RMCategoryId { get; set; }
        public string RMMaterialFunction { get; set; }
        public string RMSpecNumber { get; set; }
        public string SalesRevenue { get; set; }
        public Nullable<long> ShelfLife { get; set; }
        public Nullable<System.DateTime> ShipToTradeDate { get; set; }
        public string SpecialStorageConditions { get; set; }
        public Nullable<System.DateTime> SteeringCommitteeApproveDate { get; set; }
        public Nullable<System.DateTime> SteeringCommitteeReviewDate { get; set; }
        public string SupplierName { get; set; }
        public Nullable<long> SupplierSegmentation { get; set; }
        public string TemplateName { get; set; }
        public string TradeName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialFollowupItem> MaterialFollowupItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectBrand> ProjectBrands { get; set; }
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectSupplier> ProjectSuppliers { get; set; }
    }
}
