//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.Activities = new HashSet<Activity>();
            this.Attachments = new HashSet<Attachment>();
            this.Notes = new HashSet<Note>();
            this.Tasks1 = new HashSet<Task>();
            this.Tasks = new HashSet<Task>();
            this.Users = new HashSet<User>();
        }
    
        public long TaskId { get; set; }
        public Nullable<System.DateTime> ActualEndDate { get; set; }
        public Nullable<System.DateTime> ActualStartDate { get; set; }
        public bool AreDatesModified { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> FixedCost { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public long MilestoneId { get; set; }
        public double PercentComplete { get; set; }
        public long ProjectId { get; set; }
        public Nullable<long> SNo { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string TaskDescription { get; set; }
        public string TaskDisplayId { get; set; }
        public string TaskName { get; set; }
        public Nullable<long> TaskNumber { get; set; }
        public Nullable<long> TaskStatusId { get; set; }
        public Nullable<decimal> VaribaleCost { get; set; }
        public Nullable<long> WorkstreamId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attachment> Attachments { get; set; }
        public virtual Milestone Milestone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Note> Notes { get; set; }
        public virtual Project Project { get; set; }
        public virtual TaskStatu TaskStatu { get; set; }
        public virtual Workstream Workstream { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
