//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectData
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Activities = new HashSet<Activity>();
            this.Activities1 = new HashSet<Activity>();
            this.Attachments = new HashSet<Attachment>();
            this.Checklists = new HashSet<Checklist>();
            this.LogReadActivities = new HashSet<LogReadActivity>();
            this.LogReadAlerts = new HashSet<LogReadAlert>();
            this.MiscellaneousForms = new HashSet<MiscellaneousForm>();
            this.MiscellaneousForms1 = new HashSet<MiscellaneousForm>();
            this.MiscellaneousForms2 = new HashSet<MiscellaneousForm>();
            this.MiscellaneousForms3 = new HashSet<MiscellaneousForm>();
            this.MiscellaneousForms4 = new HashSet<MiscellaneousForm>();
            this.MiscellaneousForms5 = new HashSet<MiscellaneousForm>();
            this.MiscellaneousForms6 = new HashSet<MiscellaneousForm>();
            this.MiscellaneousForms7 = new HashSet<MiscellaneousForm>();
            this.Notes = new HashSet<Note>();
            this.PmcSrcmForms = new HashSet<PmcSrcmForm>();
            this.PmcSrcmForms1 = new HashSet<PmcSrcmForm>();
            this.PmcSrcmForms2 = new HashSet<PmcSrcmForm>();
            this.PmcSrcmForms3 = new HashSet<PmcSrcmForm>();
            this.PmcSrcmForms4 = new HashSet<PmcSrcmForm>();
            this.PmcSrcmForms5 = new HashSet<PmcSrcmForm>();
            this.PmcSrcmForms6 = new HashSet<PmcSrcmForm>();
            this.PmcSrcmForms7 = new HashSet<PmcSrcmForm>();
            this.PmcSrcmForms8 = new HashSet<PmcSrcmForm>();
            this.PmcSrcmForms9 = new HashSet<PmcSrcmForm>();
            this.ProjectAlerts = new HashSet<ProjectAlert>();
            this.Projects = new HashSet<Project>();
            this.Projects1 = new HashSet<Project>();
            this.ProjectsMonthwiseLogs = new HashSet<ProjectsMonthwiseLog>();
            this.ProjectsMonthwiseLogs1 = new HashSet<ProjectsMonthwiseLog>();
            this.ProjectsPMCSRCMMonthwiseLogs = new HashSet<ProjectsPMCSRCMMonthwiseLog>();
            this.ProjectsPMCSRCMMonthwiseLogs1 = new HashSet<ProjectsPMCSRCMMonthwiseLog>();
            this.ProjectsPMCSRCMMonthwiseLogs2 = new HashSet<ProjectsPMCSRCMMonthwiseLog>();
            this.ProjectsPMCSRCMMonthwiseLogs3 = new HashSet<ProjectsPMCSRCMMonthwiseLog>();
            this.ProjectsPMCSRCMMonthwiseLogs4 = new HashSet<ProjectsPMCSRCMMonthwiseLog>();
            this.ProjectsPMCSRCMMonthwiseLogs5 = new HashSet<ProjectsPMCSRCMMonthwiseLog>();
            this.ProjectsPMCSRCMMonthwiseLogs6 = new HashSet<ProjectsPMCSRCMMonthwiseLog>();
            this.ProjectsPMCSRCMMonthwiseLogs7 = new HashSet<ProjectsPMCSRCMMonthwiseLog>();
            this.ProjectsPMCSRCMMonthwiseLogs8 = new HashSet<ProjectsPMCSRCMMonthwiseLog>();
            this.ProjectsPMCSRCMMonthwiseLogs9 = new HashSet<ProjectsPMCSRCMMonthwiseLog>();
            this.ProjectsRMCSRCMMonthwiseLogs = new HashSet<ProjectsRMCSRCMMonthwiseLog>();
            this.ProjectsRMCSRCMMonthwiseLogs1 = new HashSet<ProjectsRMCSRCMMonthwiseLog>();
            this.ProjectsRMCSRCMMonthwiseLogs2 = new HashSet<ProjectsRMCSRCMMonthwiseLog>();
            this.ProjectsRMCSRCMMonthwiseLogs3 = new HashSet<ProjectsRMCSRCMMonthwiseLog>();
            this.ProjectsRMCSRCMMonthwiseLogs4 = new HashSet<ProjectsRMCSRCMMonthwiseLog>();
            this.ProjectsRMCSRCMMonthwiseLogs5 = new HashSet<ProjectsRMCSRCMMonthwiseLog>();
            this.ProjectsRMCSRCMMonthwiseLogs6 = new HashSet<ProjectsRMCSRCMMonthwiseLog>();
            this.ProjectsRMCSRCMMonthwiseLogs7 = new HashSet<ProjectsRMCSRCMMonthwiseLog>();
            this.ProjectTemplates = new HashSet<ProjectTemplate>();
            this.ProjectTemplates1 = new HashSet<ProjectTemplate>();
            this.ProjectTemplates2 = new HashSet<ProjectTemplate>();
            this.RecentProjectInfoes = new HashSet<RecentProjectInfo>();
            this.RmcSrcmForms = new HashSet<RmcSrcmForm>();
            this.RmcSrcmForms1 = new HashSet<RmcSrcmForm>();
            this.RmcSrcmForms2 = new HashSet<RmcSrcmForm>();
            this.RmcSrcmForms3 = new HashSet<RmcSrcmForm>();
            this.RmcSrcmForms4 = new HashSet<RmcSrcmForm>();
            this.RmcSrcmForms5 = new HashSet<RmcSrcmForm>();
            this.RmcSrcmForms6 = new HashSet<RmcSrcmForm>();
            this.RmcSrcmForms7 = new HashSet<RmcSrcmForm>();
            this.UserSettings = new HashSet<UserSetting>();
            this.Tasks = new HashSet<Task>();
            this.Roles = new HashSet<Role>();
            this.Workstreams = new HashSet<Workstream>();
        }
    
        public long UserId { get; set; }
        public Nullable<System.DateTime> AccountValidFrom { get; set; }
        public Nullable<System.DateTime> AccountValidTo { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long DesignationId { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public Nullable<long> FunctionalGroupId { get; set; }
        public bool IsBlocked { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsNonSystemUser { get; set; }
        public string LandPhone { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string LastName { get; set; }
        public string Mobile { get; set; }
        public string Password { get; set; }
        public string PhotoFilePath { get; set; }
        public string UserName { get; set; }
        public Nullable<long> WorkstreamId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activities1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attachment> Attachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Checklist> Checklists { get; set; }
        public virtual Designation Designation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogReadActivity> LogReadActivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogReadAlert> LogReadAlerts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MiscellaneousForm> MiscellaneousForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MiscellaneousForm> MiscellaneousForms1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MiscellaneousForm> MiscellaneousForms2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MiscellaneousForm> MiscellaneousForms3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MiscellaneousForm> MiscellaneousForms4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MiscellaneousForm> MiscellaneousForms5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MiscellaneousForm> MiscellaneousForms6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MiscellaneousForm> MiscellaneousForms7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Note> Notes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PmcSrcmForm> PmcSrcmForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PmcSrcmForm> PmcSrcmForms1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PmcSrcmForm> PmcSrcmForms2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PmcSrcmForm> PmcSrcmForms3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PmcSrcmForm> PmcSrcmForms4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PmcSrcmForm> PmcSrcmForms5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PmcSrcmForm> PmcSrcmForms6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PmcSrcmForm> PmcSrcmForms7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PmcSrcmForm> PmcSrcmForms8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PmcSrcmForm> PmcSrcmForms9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectAlert> ProjectAlerts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project> Projects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project> Projects1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectsMonthwiseLog> ProjectsMonthwiseLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectsMonthwiseLog> ProjectsMonthwiseLogs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectsPMCSRCMMonthwiseLog> ProjectsPMCSRCMMonthwiseLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectsPMCSRCMMonthwiseLog> ProjectsPMCSRCMMonthwiseLogs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectsPMCSRCMMonthwiseLog> ProjectsPMCSRCMMonthwiseLogs2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectsPMCSRCMMonthwiseLog> ProjectsPMCSRCMMonthwiseLogs3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectsPMCSRCMMonthwiseLog> ProjectsPMCSRCMMonthwiseLogs4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectsPMCSRCMMonthwiseLog> ProjectsPMCSRCMMonthwiseLogs5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectsPMCSRCMMonthwiseLog> ProjectsPMCSRCMMonthwiseLogs6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectsPMCSRCMMonthwiseLog> ProjectsPMCSRCMMonthwiseLogs7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectsPMCSRCMMonthwiseLog> ProjectsPMCSRCMMonthwiseLogs8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectsPMCSRCMMonthwiseLog> ProjectsPMCSRCMMonthwiseLogs9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectsRMCSRCMMonthwiseLog> ProjectsRMCSRCMMonthwiseLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectsRMCSRCMMonthwiseLog> ProjectsRMCSRCMMonthwiseLogs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectsRMCSRCMMonthwiseLog> ProjectsRMCSRCMMonthwiseLogs2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectsRMCSRCMMonthwiseLog> ProjectsRMCSRCMMonthwiseLogs3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectsRMCSRCMMonthwiseLog> ProjectsRMCSRCMMonthwiseLogs4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectsRMCSRCMMonthwiseLog> ProjectsRMCSRCMMonthwiseLogs5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectsRMCSRCMMonthwiseLog> ProjectsRMCSRCMMonthwiseLogs6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectsRMCSRCMMonthwiseLog> ProjectsRMCSRCMMonthwiseLogs7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectTemplate> ProjectTemplates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectTemplate> ProjectTemplates1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectTemplate> ProjectTemplates2 { get; set; }
        public virtual ProjectType ProjectType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecentProjectInfo> RecentProjectInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RmcSrcmForm> RmcSrcmForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RmcSrcmForm> RmcSrcmForms1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RmcSrcmForm> RmcSrcmForms2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RmcSrcmForm> RmcSrcmForms3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RmcSrcmForm> RmcSrcmForms4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RmcSrcmForm> RmcSrcmForms5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RmcSrcmForm> RmcSrcmForms6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RmcSrcmForm> RmcSrcmForms7 { get; set; }
        public virtual Workstream Workstream { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSetting> UserSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Role> Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Workstream> Workstreams { get; set; }
    }
}
