//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewProjectDetail
    {
        public long ProjectId { get; set; }
        public Nullable<System.DateTime> ActualEndDate { get; set; }
        public Nullable<System.DateTime> ActualStartDate { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> InProgressDate { get; set; }
        public bool IsDateChangeBlocked { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsMigrated { get; set; }
        public bool IsMilestoneTemplateSpecified { get; set; }
        public Nullable<long> LastMilestoneSNo { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public double PercentComplete { get; set; }
        public Nullable<long> ProjectCoordinatorId { get; set; }
        public string ProjectDisplayId { get; set; }
        public Nullable<long> ProjectManagerId { get; set; }
        public string ProjectName { get; set; }
        public long ProjectOperationStatusId { get; set; }
        public long ProjectPriorityId { get; set; }
        public long ProjectStatusId { get; set; }
        public string ProjectSummary { get; set; }
        public Nullable<long> ProjectTypeId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<long> SupplierId { get; set; }
        public Nullable<int> TransferStatus { get; set; }
        public string TransferStatusMessage { get; set; }
        public string Coordinator { get; set; }
        public string Priority { get; set; }
        public string ProjectStatus { get; set; }
        public string ProjectSuppliers { get; set; }
        public string OperationStatus { get; set; }
        public Nullable<int> RRT { get; set; }
        public Nullable<System.DateTime> PlannedCompletionDate { get; set; }
        public Nullable<System.DateTime> ActualCompletionDate { get; set; }
    }
}
